### PR TITLE
Change

### PR DESCRIPTION
**Pull request by DoaaFalioun**
Edit the database of the requests and edit the navbar of the contact page

### CODE REVIEW

**Comment by DoaaFalioun** [comment]
database of article SQL Exported in db folder

**Comment by DoaaFalioun** [comment]
warehouse admin can regestreerde items zien

**Comment by DoaaFalioun** [comment]
warehouse admin dashboard. the warehouse admin can see the items that have been returned

**Comment by AronVLD** [comment]
Needs to Fix the merge conflict before before i can merge it to the master branch

**Comment by AronVLD** [comment]
Probeer meer commentaar in je code te zetten en probeer je commit messages duidelijker te maken.

**Pull request merged**
